version: "3"
services: 
  web:
    container_name: file_service_echo_app
    build: ./
    command: go run main.go
    volumes:
      - .:/echo_app
    ports: 
      - "1236:1236"
    networks:
      - customnetwork
networks:
  customnetwork:
    driver: bridge